<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // PERU
        DB::table('provincias')->insert([
            ['id' => '1', 'ubigeo' => '0101', 'nombre' => 'Chachapoyas', 'departamento_id' => '1'],
            ['id' => '2', 'ubigeo' => '0102', 'nombre' => 'Bagua', 'departamento_id' => '1'],
            ['id' => '3', 'ubigeo' => '0103', 'nombre' => 'Bongará', 'departamento_id' => '1'],
            ['id' => '4', 'ubigeo' => '0104', 'nombre' => 'Condorcanqui', 'departamento_id' => '1'],
            ['id' => '5', 'ubigeo' => '0105', 'nombre' => 'Luya', 'departamento_id' => '1'],
            ['id' => '6', 'ubigeo' => '0106', 'nombre' => 'Rodríguez de Mendoza', 'departamento_id' => '1'],
            ['id' => '7', 'ubigeo' => '0107', 'nombre' => 'Utcubamba', 'departamento_id' => '1'],
            ['id' => '8', 'ubigeo' => '0201', 'nombre' => 'Huaraz', 'departamento_id' => '2'],
            ['id' => '9', 'ubigeo' => '0202', 'nombre' => 'Aija', 'departamento_id' => '2'],
            ['id' => '10', 'ubigeo' => '0203', 'nombre' => 'Antonio Raymondi', 'departamento_id' => '2'],
            ['id' => '11', 'ubigeo' => '0204', 'nombre' => 'Asunción', 'departamento_id' => '2'],
            ['id' => '12', 'ubigeo' => '0205', 'nombre' => 'Bolognesi', 'departamento_id' => '2'],
            ['id' => '13', 'ubigeo' => '0206', 'nombre' => 'Carhuaz', 'departamento_id' => '2'],
            ['id' => '14', 'ubigeo' => '0207', 'nombre' => 'Carlos Fermín Fitzcarrald', 'departamento_id' => '2'],
            ['id' => '15', 'ubigeo' => '0208', 'nombre' => 'Casma', 'departamento_id' => '2'],
            ['id' => '16', 'ubigeo' => '0209', 'nombre' => 'Corongo', 'departamento_id' => '2'],
            ['id' => '17', 'ubigeo' => '0210', 'nombre' => 'Huari', 'departamento_id' => '2'],
            ['id' => '18', 'ubigeo' => '0211', 'nombre' => 'Huarmey', 'departamento_id' => '2'],
            ['id' => '19', 'ubigeo' => '0212', 'nombre' => 'Huaylas', 'departamento_id' => '2'],
            ['id' => '20', 'ubigeo' => '0213', 'nombre' => 'Mariscal Luzuriaga', 'departamento_id' => '2'],
            ['id' => '21', 'ubigeo' => '0214', 'nombre' => 'Ocros', 'departamento_id' => '2'],
            ['id' => '22', 'ubigeo' => '0215', 'nombre' => 'Pallasca', 'departamento_id' => '2'],
            ['id' => '23', 'ubigeo' => '0216', 'nombre' => 'Pomabamba', 'departamento_id' => '2'],
            ['id' => '24', 'ubigeo' => '0217', 'nombre' => 'Recuay', 'departamento_id' => '2'],
            ['id' => '25', 'ubigeo' => '0218', 'nombre' => 'Santa', 'departamento_id' => '2'],
            ['id' => '26', 'ubigeo' => '0219', 'nombre' => 'Sihuas', 'departamento_id' => '2'],
            ['id' => '27', 'ubigeo' => '0220', 'nombre' => 'Yungay', 'departamento_id' => '2'],
            ['id' => '28', 'ubigeo' => '0301', 'nombre' => 'Abancay', 'departamento_id' => '3'],
            ['id' => '29', 'ubigeo' => '0302', 'nombre' => 'Andahuaylas', 'departamento_id' => '3'],
            ['id' => '30', 'ubigeo' => '0303', 'nombre' => 'Antabamba', 'departamento_id' => '3'],
            ['id' => '31', 'ubigeo' => '0304', 'nombre' => 'Aymaraes', 'departamento_id' => '3'],
            ['id' => '32', 'ubigeo' => '0305', 'nombre' => 'Cotabambas', 'departamento_id' => '3'],
            ['id' => '33', 'ubigeo' => '0306', 'nombre' => 'Chincheros', 'departamento_id' => '3'],
            ['id' => '34', 'ubigeo' => '0307', 'nombre' => 'Grau', 'departamento_id' => '3'],
            ['id' => '35', 'ubigeo' => '0401', 'nombre' => 'Arequipa', 'departamento_id' => '4'],
            ['id' => '36', 'ubigeo' => '0402', 'nombre' => 'Camaná', 'departamento_id' => '4'],
            ['id' => '37', 'ubigeo' => '0403', 'nombre' => 'Caravelí', 'departamento_id' => '4'],
            ['id' => '38', 'ubigeo' => '0404', 'nombre' => 'Castilla', 'departamento_id' => '4'],
            ['id' => '39', 'ubigeo' => '0405', 'nombre' => 'Caylloma', 'departamento_id' => '4'],
            ['id' => '40', 'ubigeo' => '0406', 'nombre' => 'Condesuyos', 'departamento_id' => '4'],
            ['id' => '41', 'ubigeo' => '0407', 'nombre' => 'Islay', 'departamento_id' => '4'],
            ['id' => '42', 'ubigeo' => '0408', 'nombre' => 'La Uniòn', 'departamento_id' => '4'],
            ['id' => '43', 'ubigeo' => '0501', 'nombre' => 'Huamanga', 'departamento_id' => '5'],
            ['id' => '44', 'ubigeo' => '0502', 'nombre' => 'Cangallo', 'departamento_id' => '5'],
            ['id' => '45', 'ubigeo' => '0503', 'nombre' => 'Huanca Sancos', 'departamento_id' => '5'],
            ['id' => '46', 'ubigeo' => '0504', 'nombre' => 'Huanta', 'departamento_id' => '5'],
            ['id' => '47', 'ubigeo' => '0505', 'nombre' => 'La Mar', 'departamento_id' => '5'],
            ['id' => '48', 'ubigeo' => '0506', 'nombre' => 'Lucanas', 'departamento_id' => '5'],
            ['id' => '49', 'ubigeo' => '0507', 'nombre' => 'Parinacochas', 'departamento_id' => '5'],
            ['id' => '50', 'ubigeo' => '0508', 'nombre' => 'Pàucar del Sara Sara', 'departamento_id' => '5'],
            ['id' => '51', 'ubigeo' => '0509', 'nombre' => 'Sucre', 'departamento_id' => '5'],
            ['id' => '52', 'ubigeo' => '0510', 'nombre' => 'Víctor Fajardo', 'departamento_id' => '5'],
            ['id' => '53', 'ubigeo' => '0511', 'nombre' => 'Vilcas Huamán', 'departamento_id' => '5'],
            ['id' => '54', 'ubigeo' => '0601', 'nombre' => 'Cajamarca', 'departamento_id' => '6'],
            ['id' => '55', 'ubigeo' => '0602', 'nombre' => 'Cajabamba', 'departamento_id' => '6'],
            ['id' => '56', 'ubigeo' => '0603', 'nombre' => 'Celendín', 'departamento_id' => '6'],
            ['id' => '57', 'ubigeo' => '0604', 'nombre' => 'Chota', 'departamento_id' => '6'],
            ['id' => '58', 'ubigeo' => '0605', 'nombre' => 'Contumazá', 'departamento_id' => '6'],
            ['id' => '59', 'ubigeo' => '0606', 'nombre' => 'Cutervo', 'departamento_id' => '6'],
            ['id' => '60', 'ubigeo' => '0607', 'nombre' => 'Hualgayoc', 'departamento_id' => '6'],
            ['id' => '61', 'ubigeo' => '0608', 'nombre' => 'Jaén', 'departamento_id' => '6'],
            ['id' => '62', 'ubigeo' => '0609', 'nombre' => 'San Ignacio', 'departamento_id' => '6'],
            ['id' => '63', 'ubigeo' => '0610', 'nombre' => 'San Marcos', 'departamento_id' => '6'],
            ['id' => '64', 'ubigeo' => '0611', 'nombre' => 'San Miguel', 'departamento_id' => '6'],
            ['id' => '65', 'ubigeo' => '0612', 'nombre' => 'San Pablo', 'departamento_id' => '6'],
            ['id' => '66', 'ubigeo' => '0613', 'nombre' => 'Santa Cruz', 'departamento_id' => '6'],
            ['id' => '67', 'ubigeo' => '0701', 'nombre' => 'Prov. Const. del Callao', 'departamento_id' => '7'],
            ['id' => '68', 'ubigeo' => '0801', 'nombre' => 'Cusco', 'departamento_id' => '8'],
            ['id' => '69', 'ubigeo' => '0802', 'nombre' => 'Acomayo', 'departamento_id' => '8'],
            ['id' => '70', 'ubigeo' => '0803', 'nombre' => 'Anta', 'departamento_id' => '8'],
            ['id' => '71', 'ubigeo' => '0804', 'nombre' => 'Calca', 'departamento_id' => '8'],
            ['id' => '72', 'ubigeo' => '0805', 'nombre' => 'Canas', 'departamento_id' => '8'],
            ['id' => '73', 'ubigeo' => '0806', 'nombre' => 'Canchis', 'departamento_id' => '8'],
            ['id' => '74', 'ubigeo' => '0807', 'nombre' => 'Chumbivilcas', 'departamento_id' => '8'],
            ['id' => '75', 'ubigeo' => '0808', 'nombre' => 'Espinar', 'departamento_id' => '8'],
            ['id' => '76', 'ubigeo' => '0809', 'nombre' => 'La Convención', 'departamento_id' => '8'],
            ['id' => '77', 'ubigeo' => '0810', 'nombre' => 'Paruro', 'departamento_id' => '8'],
            ['id' => '78', 'ubigeo' => '0811', 'nombre' => 'Paucartambo', 'departamento_id' => '8'],
            ['id' => '79', 'ubigeo' => '0812', 'nombre' => 'Quispicanchi', 'departamento_id' => '8'],
            ['id' => '80', 'ubigeo' => '0813', 'nombre' => 'Urubamba', 'departamento_id' => '8'],
            ['id' => '81', 'ubigeo' => '0901', 'nombre' => 'Huancavelica', 'departamento_id' => '9'],
            ['id' => '82', 'ubigeo' => '0902', 'nombre' => 'Acobamba', 'departamento_id' => '9'],
            ['id' => '83', 'ubigeo' => '0903', 'nombre' => 'Angaraes', 'departamento_id' => '9'],
            ['id' => '84', 'ubigeo' => '0904', 'nombre' => 'Castrovirreyna', 'departamento_id' => '9'],
            ['id' => '85', 'ubigeo' => '0905', 'nombre' => 'Churcampa', 'departamento_id' => '9'],
            ['id' => '86', 'ubigeo' => '0906', 'nombre' => 'Huaytará', 'departamento_id' => '9'],
            ['id' => '87', 'ubigeo' => '0907', 'nombre' => 'Tayacaja', 'departamento_id' => '9'],
            ['id' => '88', 'ubigeo' => '1001', 'nombre' => 'Huánuco', 'departamento_id' => '10'],
            ['id' => '89', 'ubigeo' => '1002', 'nombre' => 'Ambo', 'departamento_id' => '10'],
            ['id' => '90', 'ubigeo' => '1003', 'nombre' => 'Dos de Mayo', 'departamento_id' => '10'],
            ['id' => '91', 'ubigeo' => '1004', 'nombre' => 'Huacaybamba', 'departamento_id' => '10'],
            ['id' => '92', 'ubigeo' => '1005', 'nombre' => 'Huamalíes', 'departamento_id' => '10'],
            ['id' => '93', 'ubigeo' => '1006', 'nombre' => 'Leoncio Prado', 'departamento_id' => '10'],
            ['id' => '94', 'ubigeo' => '1007', 'nombre' => 'Marañón', 'departamento_id' => '10'],
            ['id' => '95', 'ubigeo' => '1008', 'nombre' => 'Pachitea', 'departamento_id' => '10'],
            ['id' => '96', 'ubigeo' => '1009', 'nombre' => 'Puerto Inca', 'departamento_id' => '10'],
            ['id' => '97', 'ubigeo' => '1010', 'nombre' => 'Lauricocha', 'departamento_id' => '10'],
            ['id' => '98', 'ubigeo' => '1011', 'nombre' => 'Yarowilca', 'departamento_id' => '10'],
            ['id' => '99', 'ubigeo' => '1101', 'nombre' => 'Ica', 'departamento_id' => '11'],
            ['id' => '100', 'ubigeo' => '1102', 'nombre' => 'Chincha', 'departamento_id' => '11'],
            ['id' => '101', 'ubigeo' => '1103', 'nombre' => 'Nasca', 'departamento_id' => '11'],
            ['id' => '102', 'ubigeo' => '1104', 'nombre' => 'Palpa', 'departamento_id' => '11'],
            ['id' => '103', 'ubigeo' => '1105', 'nombre' => 'Pisco', 'departamento_id' => '11'],
            ['id' => '104', 'ubigeo' => '1201', 'nombre' => 'Huancayo', 'departamento_id' => '12'],
            ['id' => '105', 'ubigeo' => '1202', 'nombre' => 'Concepción', 'departamento_id' => '12'],
            ['id' => '106', 'ubigeo' => '1203', 'nombre' => 'Chanchamayo', 'departamento_id' => '12'],
            ['id' => '107', 'ubigeo' => '1204', 'nombre' => 'Jauja', 'departamento_id' => '12'],
            ['id' => '108', 'ubigeo' => '1205', 'nombre' => 'Junín', 'departamento_id' => '12'],
            ['id' => '109', 'ubigeo' => '1206', 'nombre' => 'Satipo', 'departamento_id' => '12'],
            ['id' => '110', 'ubigeo' => '1207', 'nombre' => 'Tarma', 'departamento_id' => '12'],
            ['id' => '111', 'ubigeo' => '1208', 'nombre' => 'Yauli', 'departamento_id' => '12'],
            ['id' => '112', 'ubigeo' => '1209', 'nombre' => 'Chupaca', 'departamento_id' => '12'],
            ['id' => '113', 'ubigeo' => '1301', 'nombre' => 'Trujillo', 'departamento_id' => '13'],
            ['id' => '114', 'ubigeo' => '1302', 'nombre' => 'Ascope', 'departamento_id' => '13'],
            ['id' => '115', 'ubigeo' => '1303', 'nombre' => 'Bolívar', 'departamento_id' => '13'],
            ['id' => '116', 'ubigeo' => '1304', 'nombre' => 'Chepén', 'departamento_id' => '13'],
            ['id' => '117', 'ubigeo' => '1305', 'nombre' => 'Julcán', 'departamento_id' => '13'],
            ['id' => '118', 'ubigeo' => '1306', 'nombre' => 'Otuzco', 'departamento_id' => '13'],
            ['id' => '119', 'ubigeo' => '1307', 'nombre' => 'Pacasmayo', 'departamento_id' => '13'],
            ['id' => '120', 'ubigeo' => '1308', 'nombre' => 'Pataz', 'departamento_id' => '13'],
            ['id' => '121', 'ubigeo' => '1309', 'nombre' => 'Sánchez Carrión', 'departamento_id' => '13'],
            ['id' => '122', 'ubigeo' => '1310', 'nombre' => 'Santiago de Chuco', 'departamento_id' => '13'],
            ['id' => '123', 'ubigeo' => '1311', 'nombre' => 'Gran Chimú', 'departamento_id' => '13'],
            ['id' => '124', 'ubigeo' => '1312', 'nombre' => 'Virú', 'departamento_id' => '13'],
            ['id' => '125', 'ubigeo' => '1401', 'nombre' => 'Chiclayo', 'departamento_id' => '14'],
            ['id' => '126', 'ubigeo' => '1402', 'nombre' => 'Ferreñafe', 'departamento_id' => '14'],
            ['id' => '127', 'ubigeo' => '1403', 'nombre' => 'Lambayeque', 'departamento_id' => '14'],
            ['id' => '128', 'ubigeo' => '1501', 'nombre' => 'Lima', 'departamento_id' => '15'],
            ['id' => '129', 'ubigeo' => '1502', 'nombre' => 'Barranca', 'departamento_id' => '15'],
            ['id' => '130', 'ubigeo' => '1503', 'nombre' => 'Cajatambo', 'departamento_id' => '15'],
            ['id' => '131', 'ubigeo' => '1504', 'nombre' => 'Canta', 'departamento_id' => '15'],
            ['id' => '132', 'ubigeo' => '1505', 'nombre' => 'Cañete', 'departamento_id' => '15'],
            ['id' => '133', 'ubigeo' => '1506', 'nombre' => 'Huaral', 'departamento_id' => '15'],
            ['id' => '134', 'ubigeo' => '1507', 'nombre' => 'Huarochirí', 'departamento_id' => '15'],
            ['id' => '135', 'ubigeo' => '1508', 'nombre' => 'Huaura', 'departamento_id' => '15'],
            ['id' => '136', 'ubigeo' => '1509', 'nombre' => 'Oyón', 'departamento_id' => '15'],
            ['id' => '137', 'ubigeo' => '1510', 'nombre' => 'Yauyos', 'departamento_id' => '15'],
            ['id' => '138', 'ubigeo' => '1601', 'nombre' => 'Maynas', 'departamento_id' => '16'],
            ['id' => '139', 'ubigeo' => '1602', 'nombre' => 'Alto Amazonas', 'departamento_id' => '16'],
            ['id' => '140', 'ubigeo' => '1603', 'nombre' => 'Loreto', 'departamento_id' => '16'],
            ['id' => '141', 'ubigeo' => '1604', 'nombre' => 'Mariscal Ramón Castilla', 'departamento_id' => '16'],
            ['id' => '142', 'ubigeo' => '1605', 'nombre' => 'Requena', 'departamento_id' => '16'],
            ['id' => '143', 'ubigeo' => '1606', 'nombre' => 'Ucayali', 'departamento_id' => '16'],
            ['id' => '144', 'ubigeo' => '1607', 'nombre' => 'Datem del Marañón', 'departamento_id' => '16'],
            ['id' => '145', 'ubigeo' => '1608', 'nombre' => 'Putumayo', 'departamento_id' => '16'],
            ['id' => '146', 'ubigeo' => '1701', 'nombre' => 'Tambopata', 'departamento_id' => '17'],
            ['id' => '147', 'ubigeo' => '1702', 'nombre' => 'Manu', 'departamento_id' => '17'],
            ['id' => '148', 'ubigeo' => '1703', 'nombre' => 'Tahuamanu', 'departamento_id' => '17'],
            ['id' => '149', 'ubigeo' => '1801', 'nombre' => 'Mariscal Nieto', 'departamento_id' => '18'],
            ['id' => '150', 'ubigeo' => '1802', 'nombre' => 'General Sánchez Cerro', 'departamento_id' => '18'],
            ['id' => '151', 'ubigeo' => '1803', 'nombre' => 'Ilo', 'departamento_id' => '18'],
            ['id' => '152', 'ubigeo' => '1901', 'nombre' => 'Pasco', 'departamento_id' => '19'],
            ['id' => '153', 'ubigeo' => '1902', 'nombre' => 'Daniel Alcides Carrión', 'departamento_id' => '19'],
            ['id' => '154', 'ubigeo' => '1903', 'nombre' => 'Oxapampa', 'departamento_id' => '19'],
            ['id' => '155', 'ubigeo' => '2001', 'nombre' => 'Piura', 'departamento_id' => '20'],
            ['id' => '156', 'ubigeo' => '2002', 'nombre' => 'Ayabaca', 'departamento_id' => '20'],
            ['id' => '157', 'ubigeo' => '2003', 'nombre' => 'Huancabamba', 'departamento_id' => '20'],
            ['id' => '158', 'ubigeo' => '2004', 'nombre' => 'Morropón', 'departamento_id' => '20'],
            ['id' => '159', 'ubigeo' => '2005', 'nombre' => 'Paita', 'departamento_id' => '20'],
            ['id' => '160', 'ubigeo' => '2006', 'nombre' => 'Sullana', 'departamento_id' => '20'],
            ['id' => '161', 'ubigeo' => '2007', 'nombre' => 'Talara', 'departamento_id' => '20'],
            ['id' => '162', 'ubigeo' => '2008', 'nombre' => 'Sechura', 'departamento_id' => '20'],
            ['id' => '163', 'ubigeo' => '2101', 'nombre' => 'Puno', 'departamento_id' => '21'],
            ['id' => '164', 'ubigeo' => '2102', 'nombre' => 'Azángaro', 'departamento_id' => '21'],
            ['id' => '165', 'ubigeo' => '2103', 'nombre' => 'Carabaya', 'departamento_id' => '21'],
            ['id' => '166', 'ubigeo' => '2104', 'nombre' => 'Chucuito', 'departamento_id' => '21'],
            ['id' => '167', 'ubigeo' => '2105', 'nombre' => 'El Collao', 'departamento_id' => '21'],
            ['id' => '168', 'ubigeo' => '2106', 'nombre' => 'Huancané', 'departamento_id' => '21'],
            ['id' => '169', 'ubigeo' => '2107', 'nombre' => 'Lampa', 'departamento_id' => '21'],
            ['id' => '170', 'ubigeo' => '2108', 'nombre' => 'Melgar', 'departamento_id' => '21'],
            ['id' => '171', 'ubigeo' => '2109', 'nombre' => 'Moho', 'departamento_id' => '21'],
            ['id' => '172', 'ubigeo' => '2110', 'nombre' => 'San Antonio de Putina', 'departamento_id' => '21'],
            ['id' => '173', 'ubigeo' => '2111', 'nombre' => 'San Román', 'departamento_id' => '21'],
            ['id' => '174', 'ubigeo' => '2112', 'nombre' => 'Sandia', 'departamento_id' => '21'],
            ['id' => '175', 'ubigeo' => '2113', 'nombre' => 'Yunguyo', 'departamento_id' => '21'],
            ['id' => '176', 'ubigeo' => '2201', 'nombre' => 'Moyobamba', 'departamento_id' => '22'],
            ['id' => '177', 'ubigeo' => '2202', 'nombre' => 'Bellavista', 'departamento_id' => '22'],
            ['id' => '178', 'ubigeo' => '2203', 'nombre' => 'El Dorado', 'departamento_id' => '22'],
            ['id' => '179', 'ubigeo' => '2204', 'nombre' => 'Huallaga', 'departamento_id' => '22'],
            ['id' => '180', 'ubigeo' => '2205', 'nombre' => 'Lamas', 'departamento_id' => '22'],
            ['id' => '181', 'ubigeo' => '2206', 'nombre' => 'Mariscal Cáceres', 'departamento_id' => '22'],
            ['id' => '182', 'ubigeo' => '2207', 'nombre' => 'Picota', 'departamento_id' => '22'],
            ['id' => '183', 'ubigeo' => '2208', 'nombre' => 'Rioja', 'departamento_id' => '22'],
            ['id' => '184', 'ubigeo' => '2209', 'nombre' => 'San Martín', 'departamento_id' => '22'],
            ['id' => '185', 'ubigeo' => '2210', 'nombre' => 'Tocache', 'departamento_id' => '22'],
            ['id' => '186', 'ubigeo' => '2301', 'nombre' => 'Tacna', 'departamento_id' => '23'],
            ['id' => '187', 'ubigeo' => '2302', 'nombre' => 'Candarave', 'departamento_id' => '23'],
            ['id' => '188', 'ubigeo' => '2303', 'nombre' => 'Jorge Basadre', 'departamento_id' => '23'],
            ['id' => '189', 'ubigeo' => '2304', 'nombre' => 'Tarata', 'departamento_id' => '23'],
            ['id' => '190', 'ubigeo' => '2401', 'nombre' => 'Tumbes', 'departamento_id' => '24'],
            ['id' => '191', 'ubigeo' => '2402', 'nombre' => 'Contralmirante Villar', 'departamento_id' => '24'],
            ['id' => '192', 'ubigeo' => '2403', 'nombre' => 'Zarumilla', 'departamento_id' => '24'],
            ['id' => '193', 'ubigeo' => '2501', 'nombre' => 'Coronel Portillo', 'departamento_id' => '25'],
            ['id' => '194', 'ubigeo' => '2502', 'nombre' => 'Atalaya', 'departamento_id' => '25'],
            ['id' => '195', 'ubigeo' => '2503', 'nombre' => 'Padre Abad', 'departamento_id' => '25'],
            ['id' => '196', 'ubigeo' => '2504', 'nombre' => 'Purús', 'departamento_id' => '25']
        ]);
    }
}
