<link rel="stylesheet" href="{{ asset('assets/css/fontawesome.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/brands.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/chisel-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/duotone-light.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/duotone-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/duotone-thin.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/duotone.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/etch-solid.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/jelly-duo-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/jelly-fill-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/jelly-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/light.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/notdog-duo-solid.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/notdog-solid.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-duotone-light.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-duotone-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-duotone-solid.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-duotone-thin.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-light.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-solid.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/sharp-thin.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/slab-press-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/slab-regular.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/solid.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/thin.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/thumbprint-light.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/whiteboard-semibold.css') }}">
